FROM ubuntu:14.04
MAINTAINER Yo mismo

## Añadimos la clave PGP de PostgreSQL para verificación.
## Debería coincidir con
## https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

##Añadimos el respositorio de PostgreSQL's repository.
## Llamamos a la 9,3. Si cambiamos de version es posible
##que tengamos que modificar el Dockerfile
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list

##Actualizamos los repositorios de Ubuntu PostgreSQL ##
##Debemos instalar python-software-properties
###software-properties-common y PostgreSQL 9.3
RUN apt-get update && apt-get -y -q install pythonsoftware-properties software-properties-common \
 && apt-get -y -q install postgresql-9.3 postgresqlclient-9.3 postgresql-contrib-9.3

 ##Nos cambiamos al usuario postgres, que se ha creado
##al instalar postgreSQL
USER postgres

##Creamos un usuario denominado “pguser” con password
##”secret” y creamos una base de datos llamada “pgdb”
RUN /etc/init.d/postgresql start \
 && psql --command "CREATE USER pguser WITH SUPERUSER PASSWORD 'secret';" \
 && createdb -O pguser pgdb

 ##Nos cambiamos a usuario ROOT
USER root

##Permitimos que se puede acceder a PostgreSQL
##desde clientes remotos
RUN echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/9.3/main/pg_hba.conf

##PErmitimos que se pueda acceder por cualquier
##IP que tenga el contenedor
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf

